[build.environment]
  NPM_FLAGS = "--version" # prevent Netlify npm install

[build]
  base = "."
  publish = "dist"
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build && (cd dist && npx pnpm gen)"